import { DatabaseService } from "../database/database.service";
export declare class StoreHandoffsService {
    private readonly database;
    constructor(database: DatabaseService);
    private requireActiveStoreStaff;
    private synchronizeHandoffStatus;
    private loadHandoff;
    getHandoff(handoffId: string, staffUserId: string): Promise<{
        custody: {
            id: string;
            created_at: Date;
            updated_at: Date;
            released_at: Date | null;
            transaction_item_id: string;
            custody_status: string;
            received_by_staff_id: string | null;
            received_at: Date | null;
            verified_by_staff_id: string | null;
            verified_at: Date | null;
            released_by_staff_id: string | null;
            issue_notes: string | null;
        }[];
        status: string;
        id: string;
        created_at: Date;
        updated_at: Date;
        stores: {
            name: string;
            status: string;
            id: string;
            slug: string;
            city: string | null;
            state_region: string | null;
            country_code: string | null;
            verification_status: string;
            trade_mediation_enabled: boolean;
        };
        transactions: {
            status: string;
            id: string;
            seller_user_id: string | null;
            seller_store_id: string | null;
            currency_code: string;
            listing_id: string | null;
            cash_amount: import("@prisma/client-runtime-utils").Decimal;
            accepted_offer_id: string | null;
            accepted_wishlist_offer_id: string | null;
            counterparty_user_id: string | null;
            counterparty_store_id: string | null;
            transaction_type: string;
            agreed_at: Date;
        };
        transaction_id: string;
        completed_at: Date | null;
        store_id: string;
        store_notes: string | null;
        cancelled_at: Date | null;
    }>;
    receiveItem(handoffId: string, transactionItemId: string, staffUserId: string): Promise<{
        custody: {
            id: string;
            created_at: Date;
            updated_at: Date;
            released_at: Date | null;
            transaction_item_id: string;
            custody_status: string;
            received_by_staff_id: string | null;
            received_at: Date | null;
            verified_by_staff_id: string | null;
            verified_at: Date | null;
            released_by_staff_id: string | null;
            issue_notes: string | null;
        }[];
        status: string;
        id: string;
        created_at: Date;
        updated_at: Date;
        stores: {
            name: string;
            status: string;
            id: string;
            slug: string;
            city: string | null;
            state_region: string | null;
            country_code: string | null;
            verification_status: string;
            trade_mediation_enabled: boolean;
        };
        transactions: {
            status: string;
            id: string;
            seller_user_id: string | null;
            seller_store_id: string | null;
            currency_code: string;
            listing_id: string | null;
            cash_amount: import("@prisma/client-runtime-utils").Decimal;
            accepted_offer_id: string | null;
            accepted_wishlist_offer_id: string | null;
            counterparty_user_id: string | null;
            counterparty_store_id: string | null;
            transaction_type: string;
            agreed_at: Date;
        };
        transaction_id: string;
        completed_at: Date | null;
        store_id: string;
        store_notes: string | null;
        cancelled_at: Date | null;
    }>;
    verifyItem(handoffId: string, transactionItemId: string, staffUserId: string): Promise<{
        custody: {
            id: string;
            created_at: Date;
            updated_at: Date;
            released_at: Date | null;
            transaction_item_id: string;
            custody_status: string;
            received_by_staff_id: string | null;
            received_at: Date | null;
            verified_by_staff_id: string | null;
            verified_at: Date | null;
            released_by_staff_id: string | null;
            issue_notes: string | null;
        }[];
        status: string;
        id: string;
        created_at: Date;
        updated_at: Date;
        stores: {
            name: string;
            status: string;
            id: string;
            slug: string;
            city: string | null;
            state_region: string | null;
            country_code: string | null;
            verification_status: string;
            trade_mediation_enabled: boolean;
        };
        transactions: {
            status: string;
            id: string;
            seller_user_id: string | null;
            seller_store_id: string | null;
            currency_code: string;
            listing_id: string | null;
            cash_amount: import("@prisma/client-runtime-utils").Decimal;
            accepted_offer_id: string | null;
            accepted_wishlist_offer_id: string | null;
            counterparty_user_id: string | null;
            counterparty_store_id: string | null;
            transaction_type: string;
            agreed_at: Date;
        };
        transaction_id: string;
        completed_at: Date | null;
        store_id: string;
        store_notes: string | null;
        cancelled_at: Date | null;
    }>;
    releaseItem(handoffId: string, transactionItemId: string, staffUserId: string): Promise<{
        custody: {
            id: string;
            created_at: Date;
            updated_at: Date;
            released_at: Date | null;
            transaction_item_id: string;
            custody_status: string;
            received_by_staff_id: string | null;
            received_at: Date | null;
            verified_by_staff_id: string | null;
            verified_at: Date | null;
            released_by_staff_id: string | null;
            issue_notes: string | null;
        }[];
        status: string;
        id: string;
        created_at: Date;
        updated_at: Date;
        stores: {
            name: string;
            status: string;
            id: string;
            slug: string;
            city: string | null;
            state_region: string | null;
            country_code: string | null;
            verification_status: string;
            trade_mediation_enabled: boolean;
        };
        transactions: {
            status: string;
            id: string;
            seller_user_id: string | null;
            seller_store_id: string | null;
            currency_code: string;
            listing_id: string | null;
            cash_amount: import("@prisma/client-runtime-utils").Decimal;
            accepted_offer_id: string | null;
            accepted_wishlist_offer_id: string | null;
            counterparty_user_id: string | null;
            counterparty_store_id: string | null;
            transaction_type: string;
            agreed_at: Date;
        };
        transaction_id: string;
        completed_at: Date | null;
        store_id: string;
        store_notes: string | null;
        cancelled_at: Date | null;
    }>;
}
//# sourceMappingURL=store-handoffs.service.d.ts.map