import Link from "next/link";
import styles from "./page.module.css";

const sections = [
  ["Welcome to DeckDeal", "DeckDeal helps collectors organize real cards, publish trade intent, and coordinate store-mediated exchanges. Online payment settlement is not currently part of the product."],
  ["1. Choose your game", "Use the game selector in the header. Inventory, Collections, Listings, and Wishlists stay scoped to that active game."],
  ["2. Create your collector profile", "Sign in, choose a unique username, and optionally add a public display name. Clerk manages sign-in identity; Account → Profile manages your DeckDeal public identity."],
  ["3. Discover", "Browse public Collections, ordinary Listings, collector Wants, and participating local stores. Public content never gives another user access to private inventory details."],
  ["4. Add Inventory", "Inventory means cards you actually own. Add one card through catalog search or use Bulk Add for a pasted list or CSV. Choose the physical printing, language, finish, condition, and quantity truthfully."],
  ["5. Organize Collections", "A Collection is a named way to organize owned Inventory. Collections can be private, unlisted, or public. Moving a card between Collections does not change ownership."],
  ["6. Create Listings", "A Listing is an owned Inventory item you are offering. You can list one card or preflight an entire Collection; Collection listing creates ordinary individual Listings and skips unavailable or already-listed rows."],
  ["7. Create Wants and Wishlists", "A Want describes a card you want—either any acceptable printing or one exact printing. A Wishlist is a named group of Wants with quantity, condition, finish, language, cash, and trade preferences."],
  ["8. Respond to a Want", "If you own a matching registered card, use the existing Wishlist Offer flow. Formal offered cards must come from your DeckDeal Inventory; a Want never creates fake inventory or reserves a card."],
  ["9. Make and review Offers", "An Offer is a formal proposal against a Listing or Want. Pending offers do not reserve Inventory. Review exact cards and terms before accepting, rejecting, or withdrawing."],
  ["10. Choose an LGS", "An LGS is a participating physical local game store. Eligible stores can be selected as preferred mediation locations where supported."],
  ["11. Store-mediated trade", "After acceptance, both sides bring the agreed cards to the store. The custody journey is: awaiting store receipt → received by store → verified by store → trade completed and released to the recipient."],
  ["Visibility", "Private content is owner-only. Unlisted content preserves DeckDeal's direct-access behavior without normal discovery. Public Collections and Wishlists can appear on collector profiles and discovery surfaces."],
  ["Prices", "Market-reference prices are informational estimates from named providers. A seller asking price is separate. DeckDeal does not present a reference price as a guaranteed sale value."],
  ["Safety and ownership", "Inventory rows are the ownership truth. Offers and Listings reference exact registered Inventory. Store custody and verification protect the physical handoff without rewriting historical ownership records."],
];
export default function HowItWorksPage() { return <main className={styles.main}><header><p>Product guide</p><h1>How DeckDeal works</h1><span>A friendly guide from first card to a store-mediated trade.</span></header><div className={styles.grid}>{sections.map(([title, copy]) => <section key={title}><h2>{title}</h2><p>{copy}</p></section>)}</div><section className={styles.quick}><h2>Quick starts</h2><ol><li><strong>Organize:</strong> Add Inventory → create a Collection → choose its visibility.</li><li><strong>Offer a card:</strong> Open Inventory → create a Listing → review incoming Offers.</li><li><strong>Find a card:</strong> Create a Wishlist → add a Want → let owners respond with registered cards.</li></ol><Link href="/account/inventory">Open My DeckDeal</Link></section><section className={styles.faq}><h2>Common questions</h2><details><summary>Does a Wishlist mean I own the card?</summary><p>No. Inventory is what you own; a Want is what you hope to acquire.</p></details><details><summary>Does an Offer reserve cards?</summary><p>No. Pending Offers do not reserve Inventory. Reservation occurs only through the certified acceptance lifecycle.</p></details><details><summary>Can DeckDeal complete online cash payment?</summary><p>Not currently. Payment architecture is deferred; do not treat reference prices as payment or settlement.</p></details><details><summary>Can I trade without an LGS?</summary><p>The current completed trade lifecycle is store-mediated. Choose an eligible participating store when the flow requests one.</p></details></section></main>; }
