import type { AcceptWishlistOfferInput, CreateUserWishlistInput, CreateWishlistItemInput, CreateWishlistOfferInput, UpdateUserWishlistInput, UpdateWishlistItemInput } from "@repo/validation";
import { DatabaseService } from "../database/database.service";
export declare class WishlistsService {
    private readonly database;
    constructor(database: DatabaseService);
    private requireActiveUser;
    private findEligibleTradeStore;
    private requireEligibleTradeStore;
    private resolvePreferredStoreForNewWishlist;
    private getWishlistSelect;
    private getWishlistItemSelect;
    private getWishlistOfferSelect;
    private getInventoryHydrationSelect;
    private mapInventory;
    private hydrateWishlistItems;
    private hydrateWishlists;
    private validateWishlistTargetExists;
    private validateWishlistItemMergedRules;
    getUserWishlists(userId: string): Promise<any[]>;
    getUserWishlist(userId: string, wishlistId: string): Promise<any>;
    createUserWishlist(userId: string, input: CreateUserWishlistInput): Promise<any>;
    updateUserWishlist(userId: string, wishlistId: string, input: UpdateUserWishlistInput): Promise<any>;
    createWishlistItem(userId: string, wishlistId: string, input: CreateWishlistItemInput): Promise<any>;
    updateWishlistItem(userId: string, wishlistId: string, itemId: string, input: UpdateWishlistItemInput): Promise<any>;
    getPublicWishlistItems(): Promise<any[]>;
    private loadWishlistOffer;
    private hydrateWishlistOffers;
    private validateOfferedInventoryMatchesWishlistItem;
    private validateRequestedTradeItems;
    createUserWishlistOffer(userId: string, wishlistItemId: string, input: CreateWishlistOfferInput, interestId?: string): Promise<any>;
    getUserSentWishlistOffers(userId: string): Promise<any[]>;
    getUserReceivedWishlistOffers(ownerUserId: string, wishlistItemId: string): Promise<any[]>;
    withdrawUserWishlistOffer(userId: string, offerId: string): Promise<any>;
    acceptUserWishlistOffer(ownerUserId: string, offerId: string, input: AcceptWishlistOfferInput): Promise<{
        store: {
            name: string;
            id: string;
            slug: string;
            city: string | null;
            country_code: string | null;
        };
        transaction_items: any[];
        store_trade_handoffs: {
            status: string;
            id: string;
            created_at: Date;
            updated_at: Date;
            transaction_id: string;
            completed_at: Date | null;
            store_id: string;
            store_notes: string | null;
            cancelled_at: Date | null;
        };
        custody: any[];
        status: string;
        id: string;
        created_at: Date;
        updated_at: Date;
        seller_user_id: string | null;
        seller_store_id: string | null;
        currency_code: string;
        listing_id: string | null;
        cash_amount: import("@prisma/client-runtime-utils").Decimal;
        accepted_offer_id: string | null;
        accepted_wishlist_offer_id: string | null;
        counterparty_user_id: string | null;
        counterparty_store_id: string | null;
        transaction_type: string;
        agreed_at: Date;
        completed_at: Date | null;
    }>;
    rejectUserWishlistOffer(ownerUserId: string, offerId: string): Promise<any>;
}
//# sourceMappingURL=wishlists.service.d.ts.map