import { colors } from "./colors";

export const semanticColors = {
  canvas: colors.neutral[50],
  surface: colors.neutral[0],
  surfaceMuted: colors.neutral[100],
  surfaceAccent: colors.primary[50],
  surfaceCool: colors.primary[100],
  surfaceWarm: colors.gold[100],
  text: colors.neutral[900],
  textMuted: colors.neutral[500],
  textInverse: colors.neutral[0],
  border: colors.neutral[200],
  borderStrong: colors.neutral[300],
  action: colors.primary[600],
  actionHover: colors.primary[700],
  actionSubtle: colors.primary[100],
  brandMidnight: colors.primary[700],
  brandDeep: colors.primary[900],
  highlight: colors.accent[500],
  brandAccentWarm: colors.gold[500],
  brandAccentWarmHover: colors.gold[700],
  marketplaceTrade: colors.accent[700],
  marketplaceTradeSurface: colors.accent[100],
  marketplaceCash: colors.primary[600],
  marketplaceCashSurface: colors.primary[100],
  marketplaceMixed: colors.indigo[500],
  marketplaceMixedSurface: colors.indigo[100],
  marketplaceSpecial: colors.violet[700],
  marketplaceSpecialSurface: colors.violet[100],
  marketplaceFresh: colors.gold[700],
  marketplaceFreshSurface: colors.gold[100],
  focusRing: colors.primary[500],
  success: colors.success[700],
  successSurface: colors.success[100],
  warning: colors.warning[700],
  warningSurface: colors.warning[100],
  danger: colors.error[700],
  dangerSurface: colors.error[100],
} as const;
